from pydantic import Field
from rompy.schism.namelists.basemodel import NamelistBaseModel

class CORE(NamelistBaseModel):
    ipre: int = Field(0)
    ibc: int = Field(0)
    ibtp: int = Field(1)
    rnday: int = Field(30)
    dt: float = Field(100.0)
    msc2: int = Field(24)
    mdc2: int = Field(30)
    ntracer_gen: int = Field(2)
    ntracer_age: int = Field(4)
    sed_class: int = Field(5)
    eco_class: int = Field(27)
    nspool: int = Field(36)
    ihfskip: int = Field(864)

class OPT(NamelistBaseModel):
    ipre2: int = Field(0)
    itransport_only: int = Field(0)
    iloadtide: int = Field(0)
    loadtide_coef: float = Field(0.1)
    start_year: int = Field(2000)
    start_month: int = Field(1)
    start_day: int = Field(1)
    start_hour: int = Field(0)
    utc_start: int = Field(8)
    ics: int = Field(1)
    ihot: int = Field(0)
    ieos_type: int = Field(0)
    ieos_pres: int = Field(0)
    eos_a: float = Field(-0.1)
    eos_b: float = Field(1001.0)
    dramp: float = Field(1.0)
    drampbc: float = Field(0.0)
    iupwind_mom: int = Field(0)
    indvel: int = Field(0)
    ihorcon: int = Field(0)
    hvis_coef0: float = Field(0.025)
    ishapiro: int = Field(1)
    niter_shap: int = Field(1)
    shapiro0: float = Field(0.5)
    thetai: float = Field(0.6)
    icou_elfe_wwm: int = Field(0)
    nstep_wwm: int = Field(1)
    iwbl: int = Field(0)
    hmin_radstress: float = Field(1.0)
    drampwafo: float = Field(0.0)
    turbinj: float = Field(0.15)
    turbinjds: float = Field(1.0)
    alphaw: float = Field(0.5)
    fwvor_advxy_stokes: int = Field(1)
    fwvor_advz_stokes: int = Field(1)
    fwvor_gradpress: int = Field(1)
    fwvor_breaking: int = Field(1)
    fwvor_streaming: int = Field(1)
    fwvor_wveg: int = Field(0)
    fwvor_wveg_NL: int = Field(0)
    cur_wwm: int = Field(0)
    wafo_obcramp: int = Field(0)
    imm: int = Field(0)
    ibdef: int = Field(10)
    slam0: int = Field(-124)
    sfea0: int = Field(45)
    iunder_deep: int = Field(0)
    h1_bcc: float = Field(50.0)
    h2_bcc: float = Field(100.0)
    hw_depth: str = Field('1.e6')
    hw_ratio: float = Field(0.5)
    ihydraulics: int = Field(0)
    if_source: int = Field(0)
    dramp_ss: int = Field(2)
    meth_sink: int = Field(1)
    level_age: list = Field([9, -999])
    ihdif: int = Field(0)
    nchi: int = Field(0)
    dzb_min: float = Field(0.5)
    hmin_man: float = Field(1.0)
    ncor: int = Field(0)
    rlatitude: int = Field(46)
    coricoef: int = Field(0)
    ic_elev: int = Field(0)
    nramp_elev: int = Field(0)
    inv_atm_bnd: int = Field(0)
    prmsl_ref: float = Field(101325.0)
    gen_wsett: int = Field(0)
    ibcc_mean: int = Field(0)
    rmaxvel: float = Field(5.0)
    velmin_btrack: str = Field('1.e-4')
    btrack_nudge: str = Field('9.013e-3')
    ihhat: int = Field(1)
    inunfl: int = Field(0)
    h0: float = Field(0.01)
    shorewafo: int = Field(0)
    moitn0: int = Field(50)
    mxitn0: int = Field(1500)
    rtol0: str = Field('1.e-12')
    nadv: int = Field(1)
    dtb_max: float = Field(30.0)
    dtb_min: float = Field(10.0)
    inter_mom: int = Field(0)
    kr_co: int = Field(1)
    itr_met: int = Field(3)
    h_tvd: float = Field(5.0)
    eps1_tvd_imp: str = Field('1.e-4')
    eps2_tvd_imp: str = Field('1.e-14')
    ielm_transport: int = Field(0)
    max_subcyc: int = Field(10)
    ip_weno: int = Field(2)
    courant_weno: float = Field(0.5)
    nquad: int = Field(2)
    ntd_weno: int = Field(1)
    epsilon1: str = Field('1.e-15')
    epsilon2: str = Field('1.e-10')
    i_prtnftl_weno: int = Field(0)
    epsilon3: str = Field('1.e-25')
    ielad_weno: int = Field(0)
    small_elad: str = Field('1.e-4')
    nws: int = Field(0)
    wtiminc: float = Field(150.0)
    drampwind: float = Field(1.0)
    iwindoff: int = Field(0)
    iwind_form: int = Field(1)
    model_type_pahm: int = Field(10)
    ihconsv: int = Field(0)
    isconsv: int = Field(0)
    i_hmin_airsea_ex: int = Field(2)
    hmin_airsea_ex: float = Field(0.2)
    i_hmin_salt_ex: int = Field(2)
    hmin_salt_ex: float = Field(0.2)
    iprecip_off_bnd: int = Field(0)
    itur: int = Field(3)
    dfv0: str = Field('1.e-2')
    dfh0: str = Field('1.e-4')
    mid: str = Field("'KL'")
    stab: str = Field("'KC'")
    xlsc0: float = Field(0.1)
    inu_elev: int = Field(0)
    inu_uv: int = Field(0)
    nu_sum_mult: int = Field(1)

class VERTICAL(NamelistBaseModel):
    vnh1: int = Field(400)
    vnf1: float = Field(0.0)
    vnh2: int = Field(500)
    vnf2: float = Field(0.0)
    step_nu_tr: float = Field(86400.0)
    h_bcc1: float = Field(100.0)
    s1_mxnbt: float = Field(0.5)
    s2_mxnbt: float = Field(3.5)
    iharind: int = Field(0)
    iflux: int = Field(0)
    izonal5: int = Field(0)
    ibtrack_test: int = Field(0)
    irouse_test: int = Field(0)
    flag_fib: int = Field(1)
    slr_rate: float = Field(120.0)
    isav: int = Field(0)
    nstep_ice: int = Field(1)
    rearth_pole: float = Field(6378206.4)
    rearth_eq: float = Field(6378206.4)
    shw: str = Field('4184.d0')
    rho0: str = Field('1000.d0')
    vclose_surf_frac: float = Field(1.0)
    h_massconsv: float = Field(2.0)
    rinflation_icm: str = Field('1.e-3')

class SCHOUT(NamelistBaseModel):
    nc_out: int = Field(1)
    iof_ugrid: int = Field(0)
    nhot: int = Field(0)
    nhot_write: int = Field(8640)
    iout_sta: int = Field(0)
    nspool_sta: int = Field(10)

class PARAM(NamelistBaseModel):
    """
        !parameter inputs via namelist convention.
    !(1) Use ' ' (single quotes) for chars;
    !(2) integer values are fine for real vars/arrays;
    !(3) if multiple entries for a parameter are found, the last one wins - please avoid this
    !(4) array inputs follow column major (like FORTRAN) and can spill to multiple lines. 
    !    Values can be separated by commas or spaces.
    !(5) space allowed before/after '='
    
    
    """
    CORE: CORE = CORE()
    OPT: OPT = OPT()
    VERTICAL: VERTICAL = VERTICAL()
    SCHOUT: SCHOUT = SCHOUT()
