from pydantic import Field
from rompy.schism.namelists.basemodel import NamelistBaseModel

class SED_CORE(NamelistBaseModel):
    Sd50: list = Field(['0.12d0', ' 0.18d0', ' 0.39d0', ' 0.60d0', ' 1.2d0'])
    Erate: list = Field(['1.6d-3', ' 1.6d-3', ' 1.6d-3', ' 1.6d-3', ' 1.6d-3 '])

class SED_OPT(NamelistBaseModel):
    iSedtype: list = Field([1, 1, 1, 1, 1])
    Srho: list = Field(['2650.0d0', ' 2650.0d0', ' 2650.0d0', ' 2650.0d0', ' 2650.0d0'])
    comp_ws: int = Field(0)
    comp_tauce: int = Field(0)
    Wsed: list = Field(['1.06d0', ' 3.92d0', ' 5.43d0', ' 10.19d0', ' 28.65d0'])
    tau_ce: list = Field(['0.15d0', ' 0.17d0', ' 0.23d0', ' 0.3d0', ' 0.6d0'])
    sed_debug: int = Field(0)
    ised_dump: int = Field(0)
    bedload: int = Field(1)
    bedload_filter: int = Field(0)
    bedload_limiter: int = Field(0)
    suspended_load: int = Field(1)
    iasym: int = Field(0)
    w_asym_max: str = Field('0.4d0')
    elfrink_filter: int = Field(0)
    ech_uorb: int = Field(200)
    bedload_acc: int = Field(0)
    bedload_acc_filter: int = Field(0)
    kacc_hoe: str = Field('1.4d-4')
    kacc_dub: str = Field('0.631d-4')
    thresh_acc_opt: int = Field(2)
    acrit: str = Field('0.2d0')
    tau_option: int = Field(1)
    tau_max: str = Field('10.0d0')
    zstress: str = Field('0.2d0')
    ierosion: int = Field(0)
    slope_formulation: int = Field(4)
    alpha_bs: str = Field('1.0d0')
    alpha_bn: str = Field('1.5d0')
    ised_bc_bot: int = Field(1)
    alphd: float = Field(1.0)
    refht: float = Field(0.75)
    Tbp: float = Field(100.0)
    im_pick_up: int = Field(4)
    sed_morph: int = Field(0)
    sed_morph_time: str = Field('1.d0')
    morph_fac: str = Field('1.0d0')
    drag_formulation: int = Field(1)
    ddensed: int = Field(0)
    bedforms_rough: int = Field(0)
    iwave_ripple: int = Field(1)
    irough_bdld: int = Field(1)
    slope_avalanching: int = Field(1)
    dry_slope_cr: float = Field(1.0)
    wet_slope_cr: float = Field(0.3)
    bedmass_filter: int = Field(0)
    bedmass_threshold: float = Field(0.025)
    bdldiffu: float = Field(0.5)
    bedload_coeff: str = Field('1.0d0')
    Cdb_min: str = Field('1.d-6')
    Cdb_max: float = Field(0.01)
    actv_max: str = Field('0.05d0')
    Nbed: int = Field(1)
    sedlay_ini_opt: int = Field(0)
    toplay_inithick: str = Field('10.0d-2')
    newlayer_thick: str = Field('0.001d0')
    imeth_bed_evol: int = Field(2)
    poro_option: int = Field(1)
    porosity: float = Field(0.4)
    Awooster: float = Field(0.42)
    Bwooster: float = Field(-0.458)

class SEDIMENT(NamelistBaseModel):
    """
        !  Non-cohesive Sediment Model Parameters.
    !! May 2020                                                        !
    
    !Core parameters
    
    """
    SED_CORE: SED_CORE = SED_CORE()
    SED_OPT: SED_OPT = SED_OPT()
